version: "3"
services:

#  nginx:
#    image: nginx:1.15-alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./conf/nginx:/etc/nginx/conf.d

  nginx:
    image: owasp/modsecurity
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  certbot:
      image: certbot/certbot

  app:
    container_name: deepshare_api
    image: "node:8"
    restart: always

    environment:
      - MONGO_DATABASE_URL=mongodb://mongo:27017/DeepShare

    build: .

    ports:
      - "8080:8080"

    depends_on:
      - mongo

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: "npm start"

  stage:
    container_name: deepshare_api
    image: "node"
    restart: always

    environment:
      - MONGO_DATABASE_URL=mongodb://mongo:27017/DeepShare

    build: .

    ports:
      - "8081:8081"

    depends_on:
      - mongo

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: "npm start"

  mongo:
    container_name: mongo
    image: mongo

    ports:
      - "27017:27017"
