version: "3"
services:
  app:
    container_name: deepshare_api
    image: "node:8"
    restart: always
    environment:
      - MONGO_DATABASE_URL=mongodb://mongo:27017/DeepShare
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm start"

  stage:
    container_name: deepshare_api_staging
    image: "node"
    restart: always
    environment:
      - MONGO_DATABASE_URL=mongodb://mongo:27017/DeepShare
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm start"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
